//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAnimalServiceClient2.IISHostServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Animal", Namespace="http://schemas.datacontract.org/2004/07/WcfAnimalServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Animal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IISHostServiceReference.IAnimalSvcLibrary")]
    public interface IAnimalSvcLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalSvcLibrary/GreetAnimal", ReplyAction="http://tempuri.org/IAnimalSvcLibrary/GreetAnimalResponse")]
        string GreetAnimal(WcfAnimalServiceClient2.IISHostServiceReference.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalSvcLibrary/GreetAnimal", ReplyAction="http://tempuri.org/IAnimalSvcLibrary/GreetAnimalResponse")]
        System.Threading.Tasks.Task<string> GreetAnimalAsync(WcfAnimalServiceClient2.IISHostServiceReference.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalSvcLibrary/AddAnimal", ReplyAction="http://tempuri.org/IAnimalSvcLibrary/AddAnimalResponse")]
        string AddAnimal(WcfAnimalServiceClient2.IISHostServiceReference.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalSvcLibrary/AddAnimal", ReplyAction="http://tempuri.org/IAnimalSvcLibrary/AddAnimalResponse")]
        System.Threading.Tasks.Task<string> AddAnimalAsync(WcfAnimalServiceClient2.IISHostServiceReference.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalSvcLibrary/getAnimals", ReplyAction="http://tempuri.org/IAnimalSvcLibrary/getAnimalsResponse")]
        WcfAnimalServiceClient2.IISHostServiceReference.Animal[] getAnimals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalSvcLibrary/getAnimals", ReplyAction="http://tempuri.org/IAnimalSvcLibrary/getAnimalsResponse")]
        System.Threading.Tasks.Task<WcfAnimalServiceClient2.IISHostServiceReference.Animal[]> getAnimalsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnimalSvcLibraryChannel : WcfAnimalServiceClient2.IISHostServiceReference.IAnimalSvcLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnimalSvcLibraryClient : System.ServiceModel.ClientBase<WcfAnimalServiceClient2.IISHostServiceReference.IAnimalSvcLibrary>, WcfAnimalServiceClient2.IISHostServiceReference.IAnimalSvcLibrary {
        
        public AnimalSvcLibraryClient() {
        }
        
        public AnimalSvcLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnimalSvcLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnimalSvcLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnimalSvcLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GreetAnimal(WcfAnimalServiceClient2.IISHostServiceReference.Animal animal) {
            return base.Channel.GreetAnimal(animal);
        }
        
        public System.Threading.Tasks.Task<string> GreetAnimalAsync(WcfAnimalServiceClient2.IISHostServiceReference.Animal animal) {
            return base.Channel.GreetAnimalAsync(animal);
        }
        
        public string AddAnimal(WcfAnimalServiceClient2.IISHostServiceReference.Animal animal) {
            return base.Channel.AddAnimal(animal);
        }
        
        public System.Threading.Tasks.Task<string> AddAnimalAsync(WcfAnimalServiceClient2.IISHostServiceReference.Animal animal) {
            return base.Channel.AddAnimalAsync(animal);
        }
        
        public WcfAnimalServiceClient2.IISHostServiceReference.Animal[] getAnimals() {
            return base.Channel.getAnimals();
        }
        
        public System.Threading.Tasks.Task<WcfAnimalServiceClient2.IISHostServiceReference.Animal[]> getAnimalsAsync() {
            return base.Channel.getAnimalsAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IISHostServiceReference.IAnimalSvcPrivateLibrary")]
    public interface IAnimalSvcPrivateLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalSvcPrivateLibrary/GetAnimalInfo", ReplyAction="http://tempuri.org/IAnimalSvcPrivateLibrary/GetAnimalInfoResponse")]
        string GetAnimalInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalSvcPrivateLibrary/GetAnimalInfo", ReplyAction="http://tempuri.org/IAnimalSvcPrivateLibrary/GetAnimalInfoResponse")]
        System.Threading.Tasks.Task<string> GetAnimalInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnimalSvcPrivateLibraryChannel : WcfAnimalServiceClient2.IISHostServiceReference.IAnimalSvcPrivateLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnimalSvcPrivateLibraryClient : System.ServiceModel.ClientBase<WcfAnimalServiceClient2.IISHostServiceReference.IAnimalSvcPrivateLibrary>, WcfAnimalServiceClient2.IISHostServiceReference.IAnimalSvcPrivateLibrary {
        
        public AnimalSvcPrivateLibraryClient() {
        }
        
        public AnimalSvcPrivateLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnimalSvcPrivateLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnimalSvcPrivateLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnimalSvcPrivateLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAnimalInfo() {
            return base.Channel.GetAnimalInfo();
        }
        
        public System.Threading.Tasks.Task<string> GetAnimalInfoAsync() {
            return base.Channel.GetAnimalInfoAsync();
        }
    }
}
